//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSE3Test.ESSE3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://didattica.unicam.it/services/ESSE3WS", ConfigurationName="ESSE3.Esse3Ws")]
    public interface Esse3Ws {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ESSE3Test.ESSE3.fn_dologinResponse fn_dologin(ESSE3Test.ESSE3.fn_dologinRequest request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione presenta più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_dologinResponse> fn_dologinAsync(ESSE3Test.ESSE3.fn_dologinRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché lo spazio dei nomi wrapper (http://ws.esse3.frk.kion.it) del messaggio fn_dologoutRequest non corrisponde al valore predefinito (https://didattica.unicam.it/services/ESSE3WS)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ESSE3Test.ESSE3.fn_dologoutResponse fn_dologout(ESSE3Test.ESSE3.fn_dologoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_dologoutResponse> fn_dologoutAsync(ESSE3Test.ESSE3.fn_dologoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ESSE3Test.ESSE3.fn_retrieve_xmlResponse fn_retrieve_xml(ESSE3Test.ESSE3.fn_retrieve_xmlRequest request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione presenta più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xmlResponse> fn_retrieve_xmlAsync(ESSE3Test.ESSE3.fn_retrieve_xmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ESSE3Test.ESSE3.fn_retrieve_xml_lResponse fn_retrieve_xml_l(ESSE3Test.ESSE3.fn_retrieve_xml_lRequest request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione presenta più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xml_lResponse> fn_retrieve_xml_lAsync(ESSE3Test.ESSE3.fn_retrieve_xml_lRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ESSE3Test.ESSE3.fn_retrieve_xml_pResponse fn_retrieve_xml_p(ESSE3Test.ESSE3.fn_retrieve_xml_pRequest request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione presenta più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xml_pResponse> fn_retrieve_xml_pAsync(ESSE3Test.ESSE3.fn_retrieve_xml_pRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ESSE3Test.ESSE3.fn_retrieve_xml_xResponse fn_retrieve_xml_x(ESSE3Test.ESSE3.fn_retrieve_xml_xRequest request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione presenta più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xml_xResponse> fn_retrieve_xml_xAsync(ESSE3Test.ESSE3.fn_retrieve_xml_xRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ESSE3Test.ESSE3.fn_retrieve_xml_lxResponse fn_retrieve_xml_lx(ESSE3Test.ESSE3.fn_retrieve_xml_lxRequest request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione presenta più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xml_lxResponse> fn_retrieve_xml_lxAsync(ESSE3Test.ESSE3.fn_retrieve_xml_lxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        ESSE3Test.ESSE3.fn_retrieve_xml_pxResponse fn_retrieve_xml_px(ESSE3Test.ESSE3.fn_retrieve_xml_pxRequest request);
        
        // CODEGEN: Verrà generato un contratto di messaggio perché l'operazione presenta più valori restituiti.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xml_pxResponse> fn_retrieve_xml_pxAsync(ESSE3Test.ESSE3.fn_retrieve_xml_pxRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_dologin", WrapperNamespace="http://ws.esse3.frk.kion.it", IsWrapped=true)]
    public partial class fn_dologinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sid;
        
        public fn_dologinRequest() {
        }
        
        public fn_dologinRequest(string username, string password, string sid) {
            this.username = username;
            this.password = password;
            this.sid = sid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_dologinResponse", WrapperNamespace="https://didattica.unicam.it/services/ESSE3WS", IsWrapped=true)]
    public partial class fn_dologinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int fn_dologinReturn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string sid;
        
        public fn_dologinResponse() {
        }
        
        public fn_dologinResponse(int fn_dologinReturn, string sid) {
            this.fn_dologinReturn = fn_dologinReturn;
            this.sid = sid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_dologout", WrapperNamespace="http://ws.esse3.frk.kion.it", IsWrapped=true)]
    public partial class fn_dologoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sid;
        
        public fn_dologoutRequest() {
        }
        
        public fn_dologoutRequest(string sid) {
            this.sid = sid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_dologoutResponse", WrapperNamespace="https://didattica.unicam.it/services/ESSE3WS", IsWrapped=true)]
    public partial class fn_dologoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int fn_dologoutReturn;
        
        public fn_dologoutResponse() {
        }
        
        public fn_dologoutResponse(int fn_dologoutReturn) {
            this.fn_dologoutReturn = fn_dologoutReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xml", WrapperNamespace="http://ws.esse3.frk.kion.it", IsWrapped=true)]
    public partial class fn_retrieve_xmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string retrieve;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string @params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string xml;
        
        public fn_retrieve_xmlRequest() {
        }
        
        public fn_retrieve_xmlRequest(string sid, string retrieve, string @params, string xml) {
            this.sid = sid;
            this.retrieve = retrieve;
            this.@params = @params;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xmlResponse", WrapperNamespace="https://didattica.unicam.it/services/ESSE3WS", IsWrapped=true)]
    public partial class fn_retrieve_xmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int fn_retrieve_xmlReturn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xml;
        
        public fn_retrieve_xmlResponse() {
        }
        
        public fn_retrieve_xmlResponse(int fn_retrieve_xmlReturn, string xml) {
            this.fn_retrieve_xmlReturn = fn_retrieve_xmlReturn;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xml_l", WrapperNamespace="http://ws.esse3.frk.kion.it", IsWrapped=true)]
    public partial class fn_retrieve_xml_lRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string retrieve;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string @params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string xml;
        
        public fn_retrieve_xml_lRequest() {
        }
        
        public fn_retrieve_xml_lRequest(string username, string password, string retrieve, string @params, string xml) {
            this.username = username;
            this.password = password;
            this.retrieve = retrieve;
            this.@params = @params;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xml_lResponse", WrapperNamespace="https://didattica.unicam.it/services/ESSE3WS", IsWrapped=true)]
    public partial class fn_retrieve_xml_lResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int fn_retrieve_xml_lReturn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xml;
        
        public fn_retrieve_xml_lResponse() {
        }
        
        public fn_retrieve_xml_lResponse(int fn_retrieve_xml_lReturn, string xml) {
            this.fn_retrieve_xml_lReturn = fn_retrieve_xml_lReturn;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xml_p", WrapperNamespace="http://ws.esse3.frk.kion.it", IsWrapped=true)]
    public partial class fn_retrieve_xml_pRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string retrieve;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string @params;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xml;
        
        public fn_retrieve_xml_pRequest() {
        }
        
        public fn_retrieve_xml_pRequest(string retrieve, string @params, string xml) {
            this.retrieve = retrieve;
            this.@params = @params;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xml_pResponse", WrapperNamespace="https://didattica.unicam.it/services/ESSE3WS", IsWrapped=true)]
    public partial class fn_retrieve_xml_pResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int fn_retrieve_xml_pReturn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xml;
        
        public fn_retrieve_xml_pResponse() {
        }
        
        public fn_retrieve_xml_pResponse(int fn_retrieve_xml_pReturn, string xml) {
            this.fn_retrieve_xml_pReturn = fn_retrieve_xml_pReturn;
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xml_x", WrapperNamespace="http://ws.esse3.frk.kion.it", IsWrapped=true)]
    public partial class fn_retrieve_xml_xRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xmlIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlOut;
        
        public fn_retrieve_xml_xRequest() {
        }
        
        public fn_retrieve_xml_xRequest(string sid, string xmlIn, string xmlOut) {
            this.sid = sid;
            this.xmlIn = xmlIn;
            this.xmlOut = xmlOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xml_xResponse", WrapperNamespace="https://didattica.unicam.it/services/ESSE3WS", IsWrapped=true)]
    public partial class fn_retrieve_xml_xResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int fn_retrieve_xml_xReturn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xmlOut;
        
        public fn_retrieve_xml_xResponse() {
        }
        
        public fn_retrieve_xml_xResponse(int fn_retrieve_xml_xReturn, string xmlOut) {
            this.fn_retrieve_xml_xReturn = fn_retrieve_xml_xReturn;
            this.xmlOut = xmlOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xml_lx", WrapperNamespace="http://ws.esse3.frk.kion.it", IsWrapped=true)]
    public partial class fn_retrieve_xml_lxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string xmlIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string xmlOut;
        
        public fn_retrieve_xml_lxRequest() {
        }
        
        public fn_retrieve_xml_lxRequest(string username, string password, string xmlIn, string xmlOut) {
            this.username = username;
            this.password = password;
            this.xmlIn = xmlIn;
            this.xmlOut = xmlOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xml_lxResponse", WrapperNamespace="https://didattica.unicam.it/services/ESSE3WS", IsWrapped=true)]
    public partial class fn_retrieve_xml_lxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int fn_retrieve_xml_lxReturn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xmlOut;
        
        public fn_retrieve_xml_lxResponse() {
        }
        
        public fn_retrieve_xml_lxResponse(int fn_retrieve_xml_lxReturn, string xmlOut) {
            this.fn_retrieve_xml_lxReturn = fn_retrieve_xml_lxReturn;
            this.xmlOut = xmlOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xml_px", WrapperNamespace="http://ws.esse3.frk.kion.it", IsWrapped=true)]
    public partial class fn_retrieve_xml_pxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xmlIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xmlOut;
        
        public fn_retrieve_xml_pxRequest() {
        }
        
        public fn_retrieve_xml_pxRequest(string xmlIn, string xmlOut) {
            this.xmlIn = xmlIn;
            this.xmlOut = xmlOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fn_retrieve_xml_pxResponse", WrapperNamespace="https://didattica.unicam.it/services/ESSE3WS", IsWrapped=true)]
    public partial class fn_retrieve_xml_pxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int fn_retrieve_xml_pxReturn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string xmlOut;
        
        public fn_retrieve_xml_pxResponse() {
        }
        
        public fn_retrieve_xml_pxResponse(int fn_retrieve_xml_pxReturn, string xmlOut) {
            this.fn_retrieve_xml_pxReturn = fn_retrieve_xml_pxReturn;
            this.xmlOut = xmlOut;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Esse3WsChannel : ESSE3Test.ESSE3.Esse3Ws, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Esse3WsClient : System.ServiceModel.ClientBase<ESSE3Test.ESSE3.Esse3Ws>, ESSE3Test.ESSE3.Esse3Ws {
        
        public Esse3WsClient() {
        }
        
        public Esse3WsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Esse3WsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Esse3WsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Esse3WsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESSE3Test.ESSE3.fn_dologinResponse ESSE3Test.ESSE3.Esse3Ws.fn_dologin(ESSE3Test.ESSE3.fn_dologinRequest request) {
            return base.Channel.fn_dologin(request);
        }
        
        public int fn_dologin(string username, string password, ref string sid) {
            ESSE3Test.ESSE3.fn_dologinRequest inValue = new ESSE3Test.ESSE3.fn_dologinRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.sid = sid;
            ESSE3Test.ESSE3.fn_dologinResponse retVal = ((ESSE3Test.ESSE3.Esse3Ws)(this)).fn_dologin(inValue);
            sid = retVal.sid;
            return retVal.fn_dologinReturn;
        }
        
        public System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_dologinResponse> fn_dologinAsync(ESSE3Test.ESSE3.fn_dologinRequest request) {
            return base.Channel.fn_dologinAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESSE3Test.ESSE3.fn_dologoutResponse ESSE3Test.ESSE3.Esse3Ws.fn_dologout(ESSE3Test.ESSE3.fn_dologoutRequest request) {
            return base.Channel.fn_dologout(request);
        }
        
        public int fn_dologout(string sid) {
            ESSE3Test.ESSE3.fn_dologoutRequest inValue = new ESSE3Test.ESSE3.fn_dologoutRequest();
            inValue.sid = sid;
            ESSE3Test.ESSE3.fn_dologoutResponse retVal = ((ESSE3Test.ESSE3.Esse3Ws)(this)).fn_dologout(inValue);
            return retVal.fn_dologoutReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_dologoutResponse> ESSE3Test.ESSE3.Esse3Ws.fn_dologoutAsync(ESSE3Test.ESSE3.fn_dologoutRequest request) {
            return base.Channel.fn_dologoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_dologoutResponse> fn_dologoutAsync(string sid) {
            ESSE3Test.ESSE3.fn_dologoutRequest inValue = new ESSE3Test.ESSE3.fn_dologoutRequest();
            inValue.sid = sid;
            return ((ESSE3Test.ESSE3.Esse3Ws)(this)).fn_dologoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESSE3Test.ESSE3.fn_retrieve_xmlResponse ESSE3Test.ESSE3.Esse3Ws.fn_retrieve_xml(ESSE3Test.ESSE3.fn_retrieve_xmlRequest request) {
            return base.Channel.fn_retrieve_xml(request);
        }
        
        public int fn_retrieve_xml(string sid, string retrieve, string @params, ref string xml) {
            ESSE3Test.ESSE3.fn_retrieve_xmlRequest inValue = new ESSE3Test.ESSE3.fn_retrieve_xmlRequest();
            inValue.sid = sid;
            inValue.retrieve = retrieve;
            inValue.@params = @params;
            inValue.xml = xml;
            ESSE3Test.ESSE3.fn_retrieve_xmlResponse retVal = ((ESSE3Test.ESSE3.Esse3Ws)(this)).fn_retrieve_xml(inValue);
            xml = retVal.xml;
            return retVal.fn_retrieve_xmlReturn;
        }
        
        public System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xmlResponse> fn_retrieve_xmlAsync(ESSE3Test.ESSE3.fn_retrieve_xmlRequest request) {
            return base.Channel.fn_retrieve_xmlAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESSE3Test.ESSE3.fn_retrieve_xml_lResponse ESSE3Test.ESSE3.Esse3Ws.fn_retrieve_xml_l(ESSE3Test.ESSE3.fn_retrieve_xml_lRequest request) {
            return base.Channel.fn_retrieve_xml_l(request);
        }
        
        public int fn_retrieve_xml_l(string username, string password, string retrieve, string @params, ref string xml) {
            ESSE3Test.ESSE3.fn_retrieve_xml_lRequest inValue = new ESSE3Test.ESSE3.fn_retrieve_xml_lRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.retrieve = retrieve;
            inValue.@params = @params;
            inValue.xml = xml;
            ESSE3Test.ESSE3.fn_retrieve_xml_lResponse retVal = ((ESSE3Test.ESSE3.Esse3Ws)(this)).fn_retrieve_xml_l(inValue);
            xml = retVal.xml;
            return retVal.fn_retrieve_xml_lReturn;
        }
        
        public System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xml_lResponse> fn_retrieve_xml_lAsync(ESSE3Test.ESSE3.fn_retrieve_xml_lRequest request) {
            return base.Channel.fn_retrieve_xml_lAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESSE3Test.ESSE3.fn_retrieve_xml_pResponse ESSE3Test.ESSE3.Esse3Ws.fn_retrieve_xml_p(ESSE3Test.ESSE3.fn_retrieve_xml_pRequest request) {
            return base.Channel.fn_retrieve_xml_p(request);
        }
        
        public int fn_retrieve_xml_p(string retrieve, string @params, ref string xml) {
            ESSE3Test.ESSE3.fn_retrieve_xml_pRequest inValue = new ESSE3Test.ESSE3.fn_retrieve_xml_pRequest();
            inValue.retrieve = retrieve;
            inValue.@params = @params;
            inValue.xml = xml;
            ESSE3Test.ESSE3.fn_retrieve_xml_pResponse retVal = ((ESSE3Test.ESSE3.Esse3Ws)(this)).fn_retrieve_xml_p(inValue);
            xml = retVal.xml;
            return retVal.fn_retrieve_xml_pReturn;
        }
        
        public System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xml_pResponse> fn_retrieve_xml_pAsync(ESSE3Test.ESSE3.fn_retrieve_xml_pRequest request) {
            return base.Channel.fn_retrieve_xml_pAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESSE3Test.ESSE3.fn_retrieve_xml_xResponse ESSE3Test.ESSE3.Esse3Ws.fn_retrieve_xml_x(ESSE3Test.ESSE3.fn_retrieve_xml_xRequest request) {
            return base.Channel.fn_retrieve_xml_x(request);
        }
        
        public int fn_retrieve_xml_x(string sid, string xmlIn, ref string xmlOut) {
            ESSE3Test.ESSE3.fn_retrieve_xml_xRequest inValue = new ESSE3Test.ESSE3.fn_retrieve_xml_xRequest();
            inValue.sid = sid;
            inValue.xmlIn = xmlIn;
            inValue.xmlOut = xmlOut;
            ESSE3Test.ESSE3.fn_retrieve_xml_xResponse retVal = ((ESSE3Test.ESSE3.Esse3Ws)(this)).fn_retrieve_xml_x(inValue);
            xmlOut = retVal.xmlOut;
            return retVal.fn_retrieve_xml_xReturn;
        }
        
        public System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xml_xResponse> fn_retrieve_xml_xAsync(ESSE3Test.ESSE3.fn_retrieve_xml_xRequest request) {
            return base.Channel.fn_retrieve_xml_xAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESSE3Test.ESSE3.fn_retrieve_xml_lxResponse ESSE3Test.ESSE3.Esse3Ws.fn_retrieve_xml_lx(ESSE3Test.ESSE3.fn_retrieve_xml_lxRequest request) {
            return base.Channel.fn_retrieve_xml_lx(request);
        }
        
        public int fn_retrieve_xml_lx(string username, string password, string xmlIn, ref string xmlOut) {
            ESSE3Test.ESSE3.fn_retrieve_xml_lxRequest inValue = new ESSE3Test.ESSE3.fn_retrieve_xml_lxRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.xmlIn = xmlIn;
            inValue.xmlOut = xmlOut;
            ESSE3Test.ESSE3.fn_retrieve_xml_lxResponse retVal = ((ESSE3Test.ESSE3.Esse3Ws)(this)).fn_retrieve_xml_lx(inValue);
            xmlOut = retVal.xmlOut;
            return retVal.fn_retrieve_xml_lxReturn;
        }
        
        public System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xml_lxResponse> fn_retrieve_xml_lxAsync(ESSE3Test.ESSE3.fn_retrieve_xml_lxRequest request) {
            return base.Channel.fn_retrieve_xml_lxAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESSE3Test.ESSE3.fn_retrieve_xml_pxResponse ESSE3Test.ESSE3.Esse3Ws.fn_retrieve_xml_px(ESSE3Test.ESSE3.fn_retrieve_xml_pxRequest request) {
            return base.Channel.fn_retrieve_xml_px(request);
        }
        
        public int fn_retrieve_xml_px(string xmlIn, ref string xmlOut) {
            ESSE3Test.ESSE3.fn_retrieve_xml_pxRequest inValue = new ESSE3Test.ESSE3.fn_retrieve_xml_pxRequest();
            inValue.xmlIn = xmlIn;
            inValue.xmlOut = xmlOut;
            ESSE3Test.ESSE3.fn_retrieve_xml_pxResponse retVal = ((ESSE3Test.ESSE3.Esse3Ws)(this)).fn_retrieve_xml_px(inValue);
            xmlOut = retVal.xmlOut;
            return retVal.fn_retrieve_xml_pxReturn;
        }
        
        public System.Threading.Tasks.Task<ESSE3Test.ESSE3.fn_retrieve_xml_pxResponse> fn_retrieve_xml_pxAsync(ESSE3Test.ESSE3.fn_retrieve_xml_pxRequest request) {
            return base.Channel.fn_retrieve_xml_pxAsync(request);
        }
    }
}
